---
title: "Covid91 vaccine study Final2023"
author: "Andrea Calderon"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: Spring 2024 final 
---

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
require(forcats)
FinalDat <-read.csv(file="final.csv",header=TRUE)
#recode to remove the annoying "X" from the dataframe
FinalData <- FinalDat  %>% select(-one_of("X"))
FinalData <- FinalData %>%
mutate(across(where(is.character), as.factor))
```

# Introduction

A new  preventative vaccine (covid921) is under test in clinical trials. Given the nature of this vaccine it is suspected that the drug may exhibit different effectiveness across the variety of subpopulations tracked. Consider population subgroups by gender( guys and gals), drug use, and sexual orientation. Write a complete report that separately considers this drug for each subgroup and your recommendations as to whether people in the subgroup should take the vaccine. Structure your report in four sections each devoted to one of the four subgroups, use null and alternative hypothesis statements and correct statistical verbage when referencing p-values in conclusions.


$H_o$: There is no difference in the effectiveness of the covid 921 vaccine in females.

$H_a$: There is a difference in the effectiveness of the covid 921 vaccine in females.

## Methods 

The variables in this study: Males-categorical, Females-categorical, LGBT-categorical, Druggies, categorical. We will be using the Cat~Cat helper file.


## Males


## Females


## LGBTQ



## Druggies


# Overall Results and Conclusions